/* Generated by tools/png2rgb565.py - do not edit by hand */
#ifndef PET_SPRITES_H_INCLUDED
#define PET_SPRITES_H_INCLUDED

#include <stdint.h>

#define PET_SPRITES_WIDTH  32U
#define PET_SPRITES_HEIGHT 32U

extern const uint16_t pet_death_0[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_death_1[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_death_2[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_death_3[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_feed_0[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_feed_1[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_feed_2[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_feed_3[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_idle_0[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_idle_1[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_idle_2[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_idle_3[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_play_0[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_play_1[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_play_2[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_play_3[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_runaway_0[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_runaway_1[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_runaway_2[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_runaway_3[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_sleep_0[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_sleep_1[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_sleep_2[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];
extern const uint16_t pet_sleep_3[PET_SPRITES_WIDTH * PET_SPRITES_HEIGHT];

#endif /* PET_SPRITES_H_INCLUDED */
