#!/usr/bin/env python3
"""
png2rgb565.py - Convert PNG sprite frames into one RGB565 C source/header pair.

Usage (run from the repository root):
  python tools/png2rgb565.py OUT_NAME PROJECT_CORE_DIR frame1.png frame2.png ...

Example:
  python tools/png2rgb565.py pet_sprites Lab1_NUCLEO_L496/Core docs/art/frames/*.png

Writes PROJECT_CORE_DIR/Inc/OUT_NAME.h and PROJECT_CORE_DIR/Src/OUT_NAME.c.
Each PNG becomes a 'const uint16_t <file_name>[W*H]' array stored in Flash.
Transparent pixels are replaced by the background color (black).
All frames must have the same size.
"""
import glob
import os
import sys

from PIL import Image

BG = (0, 0, 0)  # background color behind transparent pixels (black)


def to_rgb565(r, g, b):
    """Pack 8-bit R, G, B into 16-bit RGB565 (same format as ILI9341_COLOR_*)."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def c_name(path):
    """File name without extension, made safe for use as a C identifier."""
    base = os.path.splitext(os.path.basename(path))[0]
    return "".join(ch if ch.isalnum() else "_" for ch in base).lower()


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)

    out_name, core_dir = sys.argv[1], sys.argv[2]

    # PowerShell does not expand * by itself, so expand patterns here
    files = []
    for pattern in sys.argv[3:]:
        files.extend(sorted(glob.glob(pattern)))
    if not files:
        sys.exit("Error: no PNG files found")

    size = None
    arrays = []
    for f in files:
        img = Image.open(f).convert("RGBA")
        if size is None:
            size = img.size
        elif img.size != size:
            sys.exit(f"Error: {f} is {img.size}, but frames must all be {size}")
        bg = Image.new("RGBA", img.size, BG + (255,))
        img = Image.alpha_composite(bg, img).convert("RGB")
        arrays.append((c_name(f), [to_rgb565(*p) for p in img.getdata()]))

    w, h = size
    up = out_name.upper()

    with open(os.path.join(core_dir, "Inc", out_name + ".h"), "w") as fh:
        fh.write("/* Generated by tools/png2rgb565.py - do not edit by hand */\n")
        fh.write(f"#ifndef {up}_H_INCLUDED\n#define {up}_H_INCLUDED\n\n")
        fh.write("#include <stdint.h>\n\n")
        fh.write(f"#define {up}_WIDTH  {w}U\n#define {up}_HEIGHT {h}U\n\n")
        for name, _ in arrays:
            fh.write(f"extern const uint16_t {name}[{up}_WIDTH * {up}_HEIGHT];\n")
        fh.write(f"\n#endif /* {up}_H_INCLUDED */\n")

    with open(os.path.join(core_dir, "Src", out_name + ".c"), "w") as fc:
        fc.write("/* Generated by tools/png2rgb565.py - do not edit by hand */\n")
        fc.write(f'#include "{out_name}.h"\n')
        for name, px in arrays:
            fc.write(f"\nconst uint16_t {name}[{up}_WIDTH * {up}_HEIGHT] = {{\n")
            for i in range(0, len(px), 12):
                fc.write("    " + ", ".join(f"0x{p:04X}" for p in px[i:i + 12]) + ",\n")
            fc.write("};\n")

    total = len(arrays) * w * h * 2
    print(f"Converted {len(arrays)} frame(s) of {w}x{h} -> {total} bytes of Flash")
    for name, _ in arrays:
        print(f"  {name}")


if __name__ == "__main__":
    main()